/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Scooters {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<Int8>;
  image_url: string | null;
  price: Numeric | null;
  source_url: string | null;
  title: string | null;
}

export interface DB {
  scooters: Scooters;
}
